---
- name: Delete dir
  file:
    path: '{{ BACKEND_BIN }}'
    state: absent

- name: Create dir
  file:
    path: '{{ BACKEND_BIN }}'
    state: directory
    recurse: yes

- name: Upload files
  synchronize:
    src: '{{ SRC_DIR }}'
    dest: '{{ BACKEND_BIN }}'
  register: copyfiles

- name: Install epel-release
  dnf:
    name: epel-release
    state: latest
  become: yes

- name: Copy script to install Erlang and elixir
  copy:
    src: ./install-erlang-elixir-el8.sh
    dest: '{{ BACKEND_BIN }}/install-erlang-elixir-el8.sh'

- name: Install Erlang and Elexir
  ansible.builtin.script: '{{ BACKEND_BIN }}/install-erlang-elixir-el8.sh'

- name: Environments
  shell: | 
     echo ${{ PATH }}
     echo ${{ FIRST_BLOCK }}
     echo ${{ DATABASE_URL }}
     echo ${{ SECRET_KEY_BASE }}
     echo ${{ CHAIN_SPEC_PATH }}
     echo ${{ COIN }}
     echo ${{ CHAIN_ID }}
     echo ${{ NETWORK }}
     echo ${{ SUBNETWORK }}
     echo ${{ ETHEREUM_JSONRPC_HTTP_URL }}
     echo ${{ ETHEREUM_JSONRPC_VARIANT }}

- name: Copy service file
  template:
    src: './{{ APPS }}'
    dest: '/etc/systemd/system/{{ APPS }}'

- name: Migrate database
  shell: mix do ecto.migrate
  args:
    chdir: '{{ BACKEND_BIN }}/apps/indexer'
  ignore_errors: yes